var express = require('express');
var app = express();
app.get('/', function(req, res) {
  var request = {};
    //request.startTime = req._startTime;
    //request.app = req.app;
    //request.body = req.body;
    //request.client = req.client;
    //request.complete = req.complete;
    //request.connection = req.connection;
    //request.cookies = req.cookies;
    //request.files = req.files;
    //request.headers = req.headers;
    //request.httpVersion = req.httpVersion;
    //request.httpVersionMajor = req.httpVersionMajor;
    //request.httpVersionMinor = req.httpVersionMinor;
    //request.method = req.method;
    //request.next = req.next;
    //request.originalUrl = req.originalUrl;
    //request.params = req.params;
    //request.query = req.query;
    //request.readable = req.readable;
    //request.route = req.route;
    //request.signedCookies = req.signedCookies;
    //request.socket = req.socket;
    //request.url = req.url;
  res.send(req.originalUrl);
});
app.listen(3001);
console.log('Listening on port 3001...');